### ISSUE TITLE
Add information about the supporting publication and funding

### ISSUE THREAD

**Issue by tvercaut** [cmower/optas#50]
For the citation, good practice is to add it in the main README.md file but also to create a CITATION.cff file at the root of the repo:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

For funding acknowledgment, the main README.md is a good place.

**Comment by cmower** [comment]
I've added the citation file and also in the readme (see #51). Todo:
- [ ] fix `CITATION.cff` (parsing error)
- [ ] @joaomoura24, could you check/update acknowledgement in `README.md` as required for your side, any changes it would be great if you could setup a PR to the `fix-issue-50` branch.
