### ISSUE TITLE
Is optas/examples.py script needed?

### ISSUE THREAD

**Issue by cmower** [cmower/optas#75]
There is a script here: https://github.com/cmower/optas/blob/master/optas/examples.py

Is this needed? Should we remove? 

@joaomoura24 I assume you are not using this for anything?

**Comment by joaomoura24** [comment]
What does the example do.
I can run it later and check what it does.
If it is something interesting we can just rename it to something more specific.

I am using some of the examples to test the new changes.

**Comment by joaomoura24** [comment]
Ok, in that case you can remove it.

**Comment by cmower** [comment]
Closing, this will be resolved when #74 is merged
